services:
  library_of_mess:
    image: library_of_mess
    build: .
    ports:
      - "${PORT}:8501"
    environment:
      LIBRARY_DIR: /library
      LIBRARY_DB: /data/library.parquet
      THUMBNAILS_DIR: /data/thumbs
    volumes:
      - ${LIBRARY_PATH}:/library:ro
      - mess-data:/data

volumes:
  mess-data:
